version: 2
references:
  objectrocket-docker-auth: &objectrocket-docker-auth
    auth:
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
  context-to-use: &context-to-use
    context: objectrocket-shared
jobs:
  test:
    docker:
    - <<: *objectrocket-docker-auth
      image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            pip install -r requirements.txt
            
workflows:
  version: 2
  test:
    jobs:
    - test: *context-to-use

  release_candidate:
    jobs:
    - test:
        <<: *context-to-use
        filters:
          tags:
            only:
            - /^[0-9]+.[0-9]+.[0-9]+rc[0-9]+$/
          branches:
            ignore: /.*/
    - release_candidate:
        <<: *context-to-use
        requires:
        - test
        filters:
          tags:
            only:
            - /^[0-9]+.[0-9]+.[0-9]+rc[0-9]+$/
          branches:
            ignore: /.*/            
